branches:
  only:
    - develop
language:
  - java
jdk:
  - openjdk7
before_install:
  # environment info
  - mvn -version
  - gradle -v
  - uname -a
  # required libs for android build tools
  - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # for gradle output style
  - export TERM=dumb
  # newest android SDK 22.6.1
  - wget http://dl.google.com/android/android-sdk_r22.6.1-linux.tgz
  - tar -zxf android-sdk_r22.6.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # manually set sdk.dir variable, according to local paths
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  # list packages for debug purpose
  - android list sdk -a -e -u
  - echo yes | android update sdk -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-19,build-tools-19.0.3 --force --no-ui
