notifications:
  email: false
  webhooks: http://n.tkte.ch/h/2560/u51lpT2YLz1Qrzqh_lTUdRLa
branches:
  only:
    - develop
language: android
android:
  components:
    - build-tools-20.0.0
    - add-on
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script: ./gradlew test